---
- name: delete tables
  tags: tables
  postgresql_table:
    name: "{{ table_name }}"
    db: "{{ hoh_db }}"
    state: absent
  loop:
    - "{{ spec_schema }}.policies"
    - "{{ spec_schema }}.placementrules"
    - "{{ spec_schema }}.placementbindings"
    - "{{ spec_schema }}.configs"
    - "{{ spec_schema }}.subscriptions"
    - "{{ spec_schema }}.channels"
    - "{{ spec_schema }}.applications"
    - "{{ history_schema }}.policies"
    - "{{ history_schema }}.placementrules"
    - "{{ history_schema }}.placementbindings"
    - "{{ history_schema }}.configs"
    - "{{ history_schema }}.subscriptions"
    - "{{ history_schema }}.channels"
    - "{{ history_schema }}.applications"
    - "{{ status_schema }}.{{ managed_clusters_table }}"
    - "{{ status_schema }}.{{ policies_table }}"
    - "{{ status_schema }}.{{ aggregated_policies_table }}"
    - "{{ status_schema }}.{{ leaf_hub_heartbeats_table }}"
    - "{{ local_spec_schema }}.policies"
    - "{{ local_spec_schema }}.placementrules"
    - "{{ local_status_schema }}.{{ policies_table }}"
  loop_control:
    loop_var: table_name
  become: yes
  become_user: postgres

- name: delete types
  tags: tables
  postgresql_query:
    db: "{{ hoh_db }}"
    query: DROP TYPE {{ item }}
  loop:
    - "{{ spec_schema}}.{{ enforcement_type }}"
    - "{{ status_schema}}.{{ compliance_type }}"
    - "{{ status_schema}}.{{ error_type }}"
  become: yes
  become_user: postgres

- name: delete functions
  tags: tables
  postgresql_query:
    db: "{{ hoh_db }}"
    query: DROP FUNCTION {{ item }}
  loop:
    - trigger_set_timestamp
    - move_policies_to_history
    - move_placementrules_to_history
    - move_placementbindings_to_history
  become: yes
  become_user: postgres
