---
- name: Stop service postgresql, if started
  service:
    name: postgresql
    state: stopped
  ignore_errors: yes

- name: uninstall postgresql
  apt:
    name:
      - postgresql
      - postgresql-client-common
      - postgresql-common
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - postgresql-contrib
      - libpq-dev
    state: absent
    purge: yes

- name: Delete postgresql directories
  file:
    state: absent
    path: '{{ item }}'
  loop:
    - /var/lib/postgresql
    - /var/log/postgresql
    - /etc/postgresql

- name: Remove the user postgres
  user:
    name: postgres
    state: absent
    remove: yes

- name: remove dependencies for ansible postgres
  pip:
    name:
      - psycopg2
    executable: pip3
    state: absent

- name: uninstall dependencies for ansible pip
  apt:
    name:
      - python3-pip
      - virtualenv
      - python-setuptools
    update_cache: yes
    state: absent
