postgresql_version: 10
hoh_db: hoh
hoh_process_user: hoh_process_user
transport_bridge_user: transport_bridge_user
spec_schema: spec
status_schema: status
transport_internal_schema: transport_internal
# according to Kubernetes DNS label standard https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
cluster_name_length_limit: 63
managed_clusters_table: managed_clusters
policies_table: compliance
aggregated_policies_table: aggregated_compliance
enforcement_type: enforcement
