---
- name: enable TLS access for the HoH Process user
  postgresql_pg_hba:
    dest: "{{ postgresql_configuration_directory }}/pg_hba.conf"
    contype: hostssl
    users: "{{ hoh_process_user }}"
    source: 0.0.0.0/0
    databases: "{{ hoh_db }}"
    method: scram-sha-256
    create: true

- name: enable TLS access for the transport bridge user
  postgresql_pg_hba:
    dest: "{{ postgresql_configuration_directory }}/pg_hba.conf"
    contype: hostssl
    users: "{{ transport_bridge_user }}"
    source: 0.0.0.0/0
    databases: "{{ hoh_db }}"
    method: scram-sha-256
    create: true

- name: set certificate file
  lineinfile:
    path: "{{ postgresql_configuration_directory }}/postgresql.conf"
    regexp: '^ssl_cert_file'
    line: ssl_cert_file = '{{ postgresql_configuration_directory }}/server.crt'
    state: present

- name: set key file
  lineinfile:
    path: "{{ postgresql_configuration_directory }}/postgresql.conf"
    regexp: '^ssl_key_file'
    line: ssl_key_file = '{{ postgresql_configuration_directory }}/server.key'
    state: present

- name: set TLS on
  lineinfile:
    path: "{{ postgresql_configuration_directory }}/postgresql.conf"
    regexp: '^ssl '
    line: ssl = on
    state: present

- name: set listen on all addresses
  lineinfile:
    path: "{{ postgresql_configuration_directory }}/postgresql.conf"
    regexp: '^listen_addresses'
    line: listen_addresses = '0.0.0.0'
    state: present

- name: restart service postgresql
  service:
    name: postgresql
    state: restarted
