---
- name: create table {{ table_name }}
  postgresql_table:
    name: "{{ status_schema }}.{{ table_name }}"
    db: "{{ hoh_db }}"
    columns:
      - policy_id uuid not null
      - cluster_name varchar({{ cluster_name_length_limit }}) not null
      - leaf_hub_name varchar({{ cluster_name_length_limit }}) not null
      - error {{ status_schema }}.{{ error_type }} not null
      - compliance {{ status_schema }}.{{ compliance_type }} not null
      - enforcement {{ spec_schema }}.{{ enforcement_type }} not null
      - resource_version text not null
  become: yes
  become_user: postgres

- name: create index on leaf_hub_name and compliance
  postgresql_idx:
    name: "{{ table_name }}_leaf_hub_non_compliant_idx"
    table: "{{ table_name }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    columns: leaf_hub_name, compliance
    cond: compliance = 'non_compliant'
  become: yes
  become_user: postgres

- name: create index on policy_id and compliance
  postgresql_idx:
    name: "{{ table_name }}_policy_id_non_compliant_idx"
    table: "{{ table_name }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    columns: policy_id, compliance
    cond: compliance = 'non_compliant'
  become: yes
  become_user: postgres

- name: create index on leaf_hub_name and cluster_name
  postgresql_idx:
    name: "{{ table_name }}_leaf_hub_cluster_idx"
    table: "{{ table_name }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    columns: leaf_hub_name, cluster_name
  become: yes
  become_user: postgres

- name: create index on policy_id, leaf_hub_name, cluster_name
  postgresql_idx:
    name: "{{ table_name }}_policy_leaf_hub_cluster_idx"
    table: "{{ table_name }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    columns: policy_id, leaf_hub_name, cluster_name
    unique: true
  become: yes
  become_user: postgres
