---
- name: create table managed_clusters
  postgresql_table:
    name: "{{ status_schema }}.{{ managed_clusters_table }}"
    db: "{{ hoh_db }}"
    columns:
      - id uuid primary key
      - leaf_hub_id uuid
      - status jsonb
      - created_at timestamp not null default now()
      - updated_at timestamp not null default now()
  become: yes
  become_user: postgres

- name: add timestamp trigger
  vars:
    table: "{{ managed_clusters_table }}"
    schema: "{{ status_schema }}"
  include_tasks: create_timestamp_trigger.yaml

- name: create table policies
  postgresql_table:
    name: "{{ status_schema }}.{{ policies_table }}"
    db: "{{ hoh_db }}"
    columns:
      - policy_id uuid primary key
      - managed_cluster_id uuid
      - status jsonb
      - created_at timestamp not null default now()
      - updated_at timestamp not null default now()
  become: yes
  become_user: postgres

- name: add timestamp trigger
  vars:
    table: "{{ policies_table }}"
    schema: "{{ status_schema }}"
  include_tasks: create_timestamp_trigger.yaml
