---
- name: create table {{ transport_internal_schema }}.{{ leaf_hub_cluster_mapping_table }}
  postgresql_table:
    name: "{{ transport_internal_schema }}.{{ leaf_hub_cluster_mapping_table }}"
    db: "{{ hoh_db }}"
    columns:
      - leaf_hub_id uuid
      - managed_cluster_name varchar({{ cluster_name_length_limit }})
      - id integer primary key
  become: yes
  become_user: postgres
