---
- name: install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
    state: present

# from https://superuser.com/a/1326644
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: install dependencies for ansible pip
  apt:
    name:
      - python3-pip
      - virtualenv
      - python-setuptools
    update_cache: yes

- name: install dependencies for ansible postgres
  pip:
    name:
      - psycopg2
    executable: pip3
