---
  # using shell inbstead of dnf task due to a certificate problem
- name: install postgresql RPM
  shell: dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  args:
      warn: false

- name: install postgresql
  dnf:
    name:
      - "postgresql{{ postgresql_version }}-server"
      - "postgresql{{ postgresql_version }}-contrib"

- name: initialize the server
  shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
  args:
    creates: "/var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf"

- name: start the server
  systemd:
    name: "postgresql-{{ postgresql_version }}"
    enabled: true
    state: started
