---
- name: install
  import_tasks: install.yaml

- name: create databases
  import_tasks: create_databases.yaml

- name: create users
  import_tasks: create_users.yaml

- name: set authorization
  tags: tables
  import_tasks: set_authorization.yaml

- name: set authentication
  import_tasks: set_authentication.yaml

- name: dump the current databases as a sanity check
  shell: psql -c '\l'
  become: yes
  become_user: postgres
  register: databases_psql_result

- debug:
    msg: "{{ databases_psql_result.stdout_lines }}"

- name: dump the current users as a sanity check
  shell: psql -c '\du'
  become: yes
  become_user: postgres
  register: databases_psql_result

- debug:
    msg: "{{ databases_psql_result.stdout_lines }}"
