---
- name: set password encryption
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^password_encryption'
    line: password_encryption = scram-sha-256
    state: present

- name: reload service postgresql
  service:
    name: postgresql
    state: reloaded
